# Generated by Django 5.2.3 on 2025-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_oauthtoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
